drop user abc@localhost; flush privileges;

create user abc@localhost identified by 'abc'

GRANT ALL PRIVILEGES ON *.* TO 'abc'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE program1_Employee

Use program1_Employee

CREATE TABLE E1(
	EMPNO INT ,
	ENAME VARCHAR(255) NOT NULL, 
	JOB VARCHAR(255) NOT NULL,
	MANAGER_NO INT NOT NULL, 
	SAL DECIMAL(10, 2) NOT NULL,
	COMMISSION DECIMAL(10, 2) NOT NULL
);

INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (2, 'Ajay Kumar M K', 'Manager', 2, 5000.00, 1000.00);

INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (7, 'Darshan', 'HRManager', 4, 7000.00, 3000.00);

INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (5, 'Deekshith', 'Tester', 8, 3000.00, 2000.00);

SELECT * FROM E1;







alter table E1 engine=innodb;

-- START A TRANSACTION 

START TRANSACTION;
INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (2, 'Ajay Kumar M K', 'Manager', 2, 5000.00, 1000.00);
INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (7, 'Darshan', 'HRManager', 4, 7000.00, 3000.00);
INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (5, 'Deekshith', 'Tester', 8, 3000.00, 2000.00);

COMMIT;

SELECT * FROM E1





START TRANSACTION;

SET SQL_SAFE_UPDATES = 0;

INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION)
VALUES (10, 'Dhakshath', 'FinanceManager', 5, 8000.00, 4000.00);

UPDATE E1 SET ENAME = 'AJAY M K' WHERE EMPNO = 2;

DELETE FROM E1 WHERE ENAME = 'Darshan';

ROLLBACK;

SELECT * FROM E1;




SET SQL_SAFE_UPDATES = 0;

ALTER TABLE E1 ADD PRIMARY KEY (EMPNO);
 



ALTER TABLE E1 MODIFY ENAME VARCHAR(255) NOT NULL

INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (3, NULL, 'clerk', 3, 50000, 20);


INSERT INTO E1 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION) 
VALUES (5, 'Prajwal', NULL,NULL, NULL, null);